### ISSUE TITLE
Date Settings more than 365 Days

### ISSUE THREAD

**Issue by highwindiest** [spsprinkles/timeline-calendar#12]
**Issue**
I want  to show a timeline of completed projects but am unable to set the days in past to render the initial view settings to anything more than 365 days.

**Describe the solution you'd like**
It would be a huge help the values in the Date settings can be set to more than 365 days.

**Comment by mikevasiloff** [comment]
I'll take a look and see if this can be added to the next update.

**Comment by mikevasiloff** [comment]
This will be added to the next release, but it won't apply to _legacy_ SharePoint calendars due to a limitation in how they are queried.

**Comment by mikevasiloff** [comment]
Fix will be in release 0.6.3+
