### ISSUE TITLE
Holiday Visualization

### ISSUE THREAD

**Issue by jerry-bishop** [spsprinkles/timeline-calendar#13]
I am not sure if this is a bug or feature request.  Based on what is happening, it appears to be a bug.

1. In edit mode, when I first type the name of my 'holiday' category in the visualization settings box, a vertical column appears down the entire calendar (i.e. across all swim lanes).
2. As soon as I 'save & close', the vertical column disappears except within the designated 'Holiday' swim lane.  The ability to hover over the holiday event for details also disappears when this visualization effect is utilized.

Ideally, the vertical bar would remain across all swim lanes to highlight any scheduling conflicts during a holiday.  Additionally, it would be nice if one could still hover over the holiday event for 'hover details'.

I appreciate your consideration of this issue.

v/r
Jerry Bishop
66th MI BDE
jerry.w.bishop6.civ@army.mil
![Edit Mode](https://github.com/spsprinkles/timeline-calendar/assets/171687317/62f117b2-5229-49f6-b5bf-48b4be50bf89)
![After Republication](https://github.com/spsprinkles/timeline-calendar/assets/171687317/57c27270-b87e-4f35-8e34-52aa781be7af)

**Comment by mikevasiloff** [comment]
The holiday vertical line issue changing is a bug I'll have to look into. As far as being unable to hover over the holiday item for the tooltip, that's a known limitation with the "background"/vertical line items. One way around that would be to have a "duplicate" holiday item shown/rendered on the calendar as a "regular" item.

**Comment by mikevasiloff** [comment]
This issue has been addressed in [version release](https://github.com/spsprinkles/timeline-calendar/releases) **0.6.3**
