### ISSUE TITLE
Fixed Category/Timeline Pane

### ISSUE THREAD

**Issue by jerry-bishop** [spsprinkles/timeline-calendar#14]
I am curious if it is possible to "freeze" the category legend and timeline such that it is still visible when scrolling down a series of swim lanes.

Thank you for your consideration,

v/r

Jerry Bishop
66 MI BDE

**Comment by mikevasiloff** [comment]
Yes, I've shared details with you over Teams regarding using the property pane option to set a fixed height as well as pointing you to the "advanced" Vis.js properties that let you set the axis orientation to "both" the top and the bottom as well as options for changing how the mouse scrolling and zooming action occurs.
