### ISSUE TITLE
short duration calendar events in the same swimlane on subsequent days hide the later event 

### ISSUE THREAD

**Issue by knocheg** [spsprinkles/timeline-calendar#3]
**Describe the bug and what *should* be happening**
Type in a clear and concise description of what the bug/issue is. Steps to reproduce should be placed in the section below.

**To Reproduce**

**Screenshots**

**Device details (please complete the following information):**
 - OS: [e.g. Windows, Smartphone (which one)]
 - Browser [e.g. Edge, Chrome]
 - Version [e.g. 118.0]

**Additional context**

**Comment by mikevasiloff** [comment]
@knocheg you didn't fill out the bug template with the details necessary to understand (and reproduce) this issue. Looking at your submission it seems you just left the base template details.

Can you provide more details on the issue, and perhaps a screenshot? If it's "sensitive" (CUI) DoD info, you can post the details (with a screenshot) in the [milBook support group](https://www.milsuite.mil/book/groups/m365-support/projects/timeline-calendar/).

**Comment by mikevasiloff** [comment]
@knocheg, do you have any details to share?

**Comment by knocheg** [comment]
Sorry, have not been able to replicate

You can consider closed/answered.


V/r
Garrett knoche
Information Management tech
G1, United States Army Europe and Africa
