### ISSUE TITLE
Calendar entry displaying at incorrect time 

### ISSUE THREAD

**Issue by WendoB** [spsprinkles/timeline-calendar#5]
**Describe the bug and what *should* be happening**
Type in a clear and concise description of what the bug/issue is. Steps to reproduce should be placed in the section below.

I created a calendar entry on a SharePoint Online (SPO) calendar with Regional Settings for time zone in Pacific time. The entry was created on Feb 21st from 11am-1pm Pacific and shows up correctly on the SPO calendar. I then added the calendar to the Timeline Calendar Web Part aka swimlane on the same site and the same entry shows as 12pm-2pm. One hour off for unknown reasons. Not good.

**To Reproduce**
1. Go to a SharePoint site with Regional Settings for Pacific time zone
2. Go to Site Contents and select Add->App->Calendar
3. Add the Events Web Part to a page and point it to this calendar
4. Add an entry on Feb 21st from 11am-1pm Pacific time. Yes I intentionally added a suffix that reads (11am-1pm PT) because I am using multiple calendars that cross time zones.5. 
5. Add the Timeline Calendar Web Part to the page and add the categories, swimlanes, and connections to the calendar(s). Scroll to Feb 21. Does your entry show up at 12-2pm like mine? It should be from 11am-1pm.6. 
**Screenshots**
1st screenshot shows the calendar entry in the correct Pacific time 11am-1pm
2-3 screenshots shows the same calendar entry on the Timeline Calendar from 12pm-2pm
![image](https://github.com/spsprinkles/timeline-calendar/assets/157745124/d945c878-a3b5-4cba-8f20-564586f3dbf7)
![image](https://github.com/spsprinkles/timeline-calendar/assets/157745124/1d317870-ddca-4869-b634-3bb87696bae4)
![image](https://github.com/spsprinkles/timeline-calendar/assets/157745124/140d8fb7-c20e-4d19-8cab-64d640c22484)

**Device details (please complete the following information):**
 - OS: [e.g. Windows 10 Enterprise
 - Browser: Edge
 - Version: 120.0.2210.144

**Additional context**
Love this web part. I really hope you get the kinks worked out because it’s solving a nationwide calendar solution conundrum for my agency.
Also, when I add the new Categories/Legend the first three are different colors. I added 6 more categories and it made them all blue/purple instead of random different colors. Now I have to spend 30 minutes and change all the colors.

Thanks and good luck.
Wendy

**Comment by mikevasiloff** [comment]
@WendoB thanks for the details. Can you share what time zone your computer itself is set to?

I'm also a bit confused on the color part and what you had to change that took 30 mins.

**Comment by WendoB** [comment]
My computer time zone is in Mountain Time. Keep in mind that I am using the Swimlane web part on calendars in all time zones. This is a nationwide thing for my agency. It’s a big deal.

The color thing is about the colors of when you add new “Categories/Legend”. There’s 3 ready to be used and they are in Green, Yellow, and Red. When I add a bunch more categories they all default to a light purple blue. It didn’t take a full 30 minutes to change the colors to different colors so they aren’t all the same light purple blue, but it is feedback for your web part. When a new category is added a random different color should be selected from the palette. 

Thanks so much for your help.

**Comment by mikevasiloff** [comment]
@WendoB, the reason the Timeline Calendar shows the events an hour different from the SP site is because it is showing them in **your** time zone as specified by your computer. The reason for this is so that people across the country/world looking at calendar events will see them in the proper time for their time zone. You can look at using the `dateInUtc` property (setting it to `false`) which is described in the "user guide" on the [milBook group](https://www.milsuite.mil/book/groups/m365-support/projects/timeline-calendar).

I understand now regarding the colors. However, I had never designed the web part to generate colors for each new category. It only provides those default three as an example.

**Comment by WendoB** [comment]
Thanks for your quick response and assistance. I am understanding how your time zones are displaying now. It confused me at first because I presumed you would be using the regional settings on the SharePoint site to determine the time zone to display a meeting. Good to know you are using the local computer time zone. I wish SharePoint would do that.
