### ISSUE TITLE
Timeline calendar rendering all day events incorrectly

### ISSUE THREAD

**Issue by harrija0** [spsprinkles/timeline-calendar#7]
When an outlook calendar event is an all day event it does not have time. When the event starts at 0:00 on the 13th and should be a two day event (end of day on the 14th) the timeline ends at 0:00 on the 14th and does not render the time. I encountered this also on DEPS implementation and added an extra 23 hours and 50 minutes for all "All Day" events. This made the event render as desired on the timeline.

Screenshot:
<img width="1184" alt="Calendar day rendering error" src="https://github.com/spsprinkles/timeline-calendar/assets/43661400/5cd82bb8-6c11-4678-a76d-575824d01b5a">

System Information: 
Device details (should be all platforms but…)
Windows 11 21H2  version 22000.2777
Browser: Edge Version 122.0.2365.80 (Official build) (64-bit)

**Comment by mikevasiloff** [comment]
@harrija0 I've _not_ been able to reproduce your scenario. Yes, I'm tracking that Outlook returns "all day event" dates with 0:00 time, but in my tests the end date is actually returned as the _next day_ to avoid this issue.

For your scenario, is this a shared mailbox/NPE calendar or an M365 Group/Team calendar? What time zone is your local computer set to? And for the person that added the event in question, do you know what time zone their profile is set to? Feel free to also contact me "externally" via Teams chat to share more info outside of this public medium.

**Comment by harrija0** [comment]
Thanks for the help. It might have been a glitch but everything is displaying correctly now. Thanks for the help!
